"""initial_schema

Revision ID: ca114e0847f1
Revises: 
Create Date: 2026-05-02 10:28:32.202544

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.models import UUIDType

# revision identifiers, used by Alembic.
revision: str = 'ca114e0847f1'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('wrapped_private_key', sa.Text(), nullable=False),
    sa.Column('pbkdf2_salt', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('from_user_id', UUIDType(length=36), nullable=False),
    sa.Column('to_user_id', UUIDType(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_deleted_at', 'messages', ['deleted_at'], unique=False)
    op.create_index('ix_messages_from_created', 'messages', ['from_user_id', 'created_at'], unique=False)
    op.create_index('ix_messages_to_created', 'messages', ['to_user_id', 'created_at'], unique=False)
    op.create_index('ix_messages_to_delivered', 'messages', ['to_user_id', 'delivered'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('user_id', UUIDType(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    sa.UniqueConstraint('token_hash', name='uq_refresh_tokens_hash')
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_user_revoked', 'refresh_tokens', ['user_id', 'revoked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_tokens_user_revoked', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_messages_to_delivered', table_name='messages')
    op.drop_index('ix_messages_to_created', table_name='messages')
    op.drop_index('ix_messages_from_created', table_name='messages')
    op.drop_index('ix_messages_deleted_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_users_deleted_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
